### PR TITLE
ServiceException debugInfo is filled with cause

### LINKED ISSUE #88: Reply with an exception without losing stack trace
I'm using generated VertxProxyHandler class for my service (`SomeServiceVertxProxyHandler. class`). 
When delivering a message through an event bus (in the case that an exception occurred during the execution), I get another exception that wraps my real one and thus losing the stacktrace.
The main problem is in this code:
```java 
 public void handle(Message<JsonObject> msg) {
    try{
      JsonObject json = msg.body();
      String action = msg.headers().get("action");
      if (action == null) throw new IllegalStateException("action not specified");
      accessed();
      switch (action) {
        case "getStart": {
          service.getStart((java.lang.String)json.getValue("tmsec"),
                        HelperUtils.createListHandler(msg));
          break;
        }
...
```
Look at the `HelperUtils.createListHandler(msg)` method:
```java
public static <T> Handler<AsyncResult<List<T>>> createListHandler(Message msg) {
    return res -> {
      if (res.failed()) {
        if (res.cause() instanceof ServiceException) {
          msg.reply(res.cause());
        } else {
          msg.reply(new ServiceException(-1, res.cause().getMessage()));
        }
```
If `res.cause()` instance of Exception (any kind of exception that may happens) and not contains message of the cause (as in case when you pass `null` in `Objects.requireNonNull()`) you will get completely another stacktrace with completely not informative message.

May be it will be better to call `initCause(Throwable t)` or  `addSuppressed(Throwable t)` to not losing original exception?

### PR DESCRIPTION
**Pull request by slinkydeveloper**
When an exception is thrown by the service or the underlying handler, include the debugging info in the `ServiceException`, that you can access using `ServiceException.getDebugInfo()`. The included info are the canonical name of the exception, the message and the stacktrace
Fixes #88

### CODE REVIEW

File: src/main/java/io/vertx/serviceproxy/HelperUtils.java [hunk 1]
```diff
@@ -108,5 +100,21 @@
     return new HashSet<T>((List<T>)list);
   }
 
+  public static JsonObject generateDebugInfo(Throwable cause) {
+    if (cause == null) return null;
+    JsonObject obj = new JsonObject();
+    obj.put("causeName", cause.getClass().getCanonicalName());
```
Comment (jponge) [inline src/main/java/io/vertx/serviceproxy/HelperUtils.java]: What if the exception has [suppressed exceptions](https://docs.oracle.com/javase/7/docs/api/java/lang/Throwable.html#getSuppressed())?

**Comment by jponge** [comment]
Hum I hit the wrong button, I have a question :-)

File: src/main/java/io/vertx/serviceproxy/HelperUtils.java (hunk 1 above)
Comment (slinkydeveloper) [reply src/main/java/io/vertx/serviceproxy/HelperUtils.java]: We can serialize them to in a field called "suppressed"

**Comment by slinkydeveloper** [comment]
Honestly I don't know if it could be useful or not, and if it increase too much the payload

**Comment by slinkydeveloper** [comment]
Maybe now we can avoid it and if someone asks for it we can add it

**Comment by jponge** [comment]
Yeah, let's keep it that way
